#!/bin/sh

: ${COLOR:=lightgreen}
: ${TITLE:=welcome to ndzsinx}

cat > /usr/share/nginx/html/index.html <<EOF
<htlm>
<body bgcolor="$COLOR">
<h1>$TITLE</h1>
$BODY
<hr/>
host: $HOSTNAME
</html>
EOF

nginx
